name: Android CI

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ALIAS: ${{secrets.ALIAS}}
      KEY_STORE_PASSWORD: ${{secrets.KEY_STORE_PASSWORD}}
      KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
      TESTFAIRY_API_KEY: ${{secrets.TESTFAIRY_API_KEY}}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: '1.0.${{github.run_number}}'

      - name: Run Workflow
        id: generateKeystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore.jks'
          encodedString: ${{secrets.SIGNING_KEY}}

      - name: Build Debug APK
        id: buildRelease
        run: ./gradlew assembleDebug

      - name: Upload APK
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk

      - name: Upload Release APK for Dev on TestFairy
        id: buildDevRelease
        env:
          SIGNING_KEY: ${{steps.generateKeystore.outputs.filePath}}
        run: ./gradlew testfairyDevRelease
        if: github.ref == 'refs/heads/dev'

      - name: Upload Release APK for Prod on TestFairy
        id: buildProdRelease
        env:
          SIGNING_KEY: ${{steps.generateKeystore.outputs.filePath}}
        run: ./gradlew testfairyProdRelease
        if: github.ref == 'refs/heads/master'